name: Pester
on:
  workflow_call:

permissions:
  pull-requests: write
  contents: read

jobs:
  test-pwsh:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Pester tests
      run: |
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -Confirm:$false -Force
        Invoke-Pester -Path "scripts/ps" -Debug -Output Detailed    
      shell: pwsh