name: "[Job] Azure Terraform Plan"

on:
  workflow_call:
    inputs:
      workspace_name:
        description: 'The terraform workspace to target for environment actions'
        required: true
        type: string
      state_storage_account_name:
        description: 'Storage account name for TF state file.'
        required: true
        type: string
    secrets:
      azure_credentials:
        description: 'JSON formatted list of azure credentials'
        required: true
      arm_client_id:
        description: 'Azure ARM Client ID'
        required: true
      arm_client_secret:
        description: 'Azure ARM Client Secret'
        required: true
      arm_tenant_id:
        description: 'ARM Tenant ID'
        required: true
      arm_subscription_id:
        description: 'ARM Subscription ID'
        required: true
      github_access_token:
        description: 'Github Token'
        required: true

permissions:
  pull-requests: write
  issues: write
  id-token: write

jobs:
  terraform_plan_workflow:
    name: "${{ inputs.workspace_name }} deployment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Export Azure Login Credentials
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.arm_client_id }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.arm_client_secret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.arm_subscription_id }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.arm_tenant_id }}" >> $GITHUB_ENV

      - name: Check formatting
        run: terraform fmt -check -recursive
        working-directory: ./terraform
        continue-on-error: true
        
      - name: Terraform Init
        run: terraform init -input=false
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
          TF_VAR_subscription_id: ${{ secrets.arm_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.arm_tenant_id }}
          TF_VAR_client_id: ${{ secrets.arm_client_id }}
          TF_VAR_client_secret: ${{ secrets.arm_client_secret }}
          TF_VAR_state_storage_account_name: ${{ inputs.state_storage_account_name }}
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
          TF_VAR_subscription_id: ${{ secrets.arm_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.arm_tenant_id }}
          TF_VAR_client_id: ${{ secrets.arm_client_id }}
          TF_VAR_client_secret: ${{ secrets.arm_client_secret }}
          TF_VAR_state_storage_account_name: ${{ inputs.state_storage_account_name }}
        working-directory: ./terraform

      - name: Terraform Plan
        id: terraform_plan
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
          TF_VAR_subscription_id: ${{ secrets.arm_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.arm_tenant_id }}
          TF_VAR_client_id: ${{ secrets.arm_client_id }}
          TF_VAR_client_secret: ${{ secrets.arm_client_secret }}
          TF_VAR_state_storage_account_name: ${{ inputs.state_storage_account_name }}
        run: |
          terraform plan -lock-timeout=300s -input=false
        working-directory: ./terraform
