name: "[Workflow] Path To Live"

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - scripts/**

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: none
  checks: none
  deployments: none
  issues: write
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  
  terraform_plan_workflow:
    strategy:
      matrix:
        environment: ["DEVL", "NLE", "LIVE", "DEVLEXTERNAL"]
    name: TF Plan ${{ matrix.environment }}
    uses: ./.github/workflows/terraform_plan_job.yml
    with:
      workspace_name: ${{ matrix.environment }}
    secrets:
      arm_subscription_id: ${{ secrets.arm_subscription_id }}
      arm_tenant_id: ${{ secrets.arm_tenant_id }}
      arm_client_id: ${{ secrets.arm_client_id }}
      arm_client_secret: ${{ secrets.arm_client_secret }}
      workspace_subscription_id: ${{ secrets.workspace_subscription_id }}
      workspace_tenant_id: ${{ secrets.workspace_tenant_id }}
      workspace_client_id: ${{ secrets.workspace_client_id }}
      workspace_client_secret: ${{ secrets.workspace_client_secret }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}

  terraform_apply_workflow:
    strategy:
      matrix:
        environment: ["DEVL", "NLE", "LIVE", "DEVLEXTERNAL"]
    needs: [terraform_plan_workflow]
    name: TF Apply ${{ matrix.environment }}
    uses: ./.github/workflows/terraform_apply_job.yml
    with:
      workspace_name: ${{ matrix.environment }}
    secrets:
      arm_subscription_id: ${{ secrets.arm_subscription_id }}
      arm_tenant_id: ${{ secrets.arm_tenant_id }}
      arm_client_id: ${{ secrets.arm_client_id }}
      arm_client_secret: ${{ secrets.arm_client_secret }}
      workspace_subscription_id: ${{ secrets.workspace_subscription_id }}
      workspace_tenant_id: ${{ secrets.workspace_tenant_id }}
      workspace_client_id: ${{ secrets.workspace_client_id }}
      workspace_client_secret: ${{ secrets.workspace_client_secret }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
